"""tabla version_modelo para el modelo semantico

Revision ID: 29bcd496a2af
Revises: ff39a100be3c
Create Date: 2026-09-08 17:18:36.118967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29bcd496a2af'
down_revision: Union[str, Sequence[str], None] = 'ff39a100be3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea la tabla version_modelo (paso 4)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version_modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operacion', sa.String(length=60), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resumen', sa.String(length=300), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], name=op.f('fk_version_modelo_autor_id_usuario'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_version_modelo_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_version_modelo')),
    sa.UniqueConstraint('workspace_id', 'numero', name=op.f('uq_version_modelo_workspace_id'))
    )
    op.create_index(op.f('ix_version_modelo_workspace_id'), 'version_modelo', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Borra la tabla version_modelo."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_modelo_workspace_id'), table_name='version_modelo')
    op.drop_table('version_modelo')
    # ### end Alembic commands ###
