"""columna perfil en fuente

Revision ID: 3b453523b1e8
Revises: ed7806959de1
Create Date: 2026-09-09 18:32:01.456706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b453523b1e8'
down_revision: Union[str, Sequence[str], None] = 'ed7806959de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Agrega fuente.perfil (perfilado, paso 9). Nullable: las fuentes ya
    ingestadas no tienen perfil hasta que se resuban."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuente', sa.Column('perfil', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Quita fuente.perfil."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuente', 'perfil')
    # ### end Alembic commands ###
