"""tabla tarea para la cola local

Revision ID: 6f0f88df11ef
Revises: c2e453e92277
Create Date: 2026-09-08 16:07:00.523174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f0f88df11ef'
down_revision: Union[str, Sequence[str], None] = 'c2e453e92277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea la tabla tarea (cola local, paso 2)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('creada_por_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'corriendo', 'terminada', 'error', name='estado_tarea', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('progreso', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mensaje', sa.String(length=300), nullable=True),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuario.id'], name=op.f('fk_tarea_creada_por_id_usuario'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_tarea_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tarea'))
    )
    op.create_index(op.f('ix_tarea_workspace_id'), 'tarea', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Borra la tabla tarea."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarea_workspace_id'), table_name='tarea')
    op.drop_table('tarea')
    # ### end Alembic commands ###
