"""tabla inferencia cache de claude

Revision ID: 822d7c18640f
Revises: 3b453523b1e8
Create Date: 2026-09-09 20:10:27.071875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '822d7c18640f'
down_revision: Union[str, Sequence[str], None] = '3b453523b1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea la tabla inferencia: cache por huella y auditoria de tokens de las
    consultas a Claude (fase 2, paso 11)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('huella', sa.String(length=32), nullable=False),
    sa.Column('modelo_claude', sa.String(length=80), nullable=False),
    sa.Column('respuesta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_salida', sa.Integer(), server_default='0', nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_inferencia_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inferencia')),
    sa.UniqueConstraint('workspace_id', 'huella', name=op.f('uq_inferencia_workspace_id'))
    )
    op.create_index(op.f('ix_inferencia_workspace_id'), 'inferencia', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Borra la tabla inferencia."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inferencia_workspace_id'), table_name='inferencia')
    op.drop_table('inferencia')
    # ### end Alembic commands ###
