"""catalogo inicial organizacion workspace usuario

Revision ID: c2e453e92277
Revises: 
Create Date: 2026-09-08 15:55:55.441698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e453e92277'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea organizacion, workspace y usuario."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizacion')),
    sa.UniqueConstraint('nombre', name=op.f('uq_organizacion_nombre'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('clave_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('plataforma', 'constructor', 'visualizador', name='rol_usuario', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(rol = 'plataforma') = (organizacion_id IS NULL)", name=op.f('ck_usuario_plataforma_sin_organizacion')),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], name=op.f('fk_usuario_organizacion_id_organizacion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    op.create_index(op.f('ix_usuario_organizacion_id'), 'usuario', ['organizacion_id'], unique=False)
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], name=op.f('fk_workspace_organizacion_id_organizacion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace')),
    sa.UniqueConstraint('organizacion_id', 'nombre', name=op.f('uq_workspace_organizacion_id'))
    )
    op.create_index(op.f('ix_workspace_organizacion_id'), 'workspace', ['organizacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Borra las tres tablas (orden inverso por las FKs)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_organizacion_id'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_usuario_organizacion_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('organizacion')
    # ### end Alembic commands ###
