"""columna diff en version_spec

Revision ID: d5e2444fad05
Revises: 822d7c18640f
Create Date: 2026-09-10 23:59:39.891240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5e2444fad05'
down_revision: Union[str, Sequence[str], None] = '822d7c18640f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Agrega version_spec.diff (paso 17, historial y deshacer): espejo de
    version_modelo.diff, nullable porque la primera version de cada
    workspace no tiene anterior contra la cual compararse."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version_spec', sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Quita version_spec.diff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('version_spec', 'diff')
    # ### end Alembic commands ###
