"""tabla version_spec para el dashboard

Revision ID: ed7806959de1
Revises: 29bcd496a2af
Create Date: 2026-09-08 17:42:54.661173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed7806959de1'
down_revision: Union[str, Sequence[str], None] = '29bcd496a2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea la tabla version_spec (paso 6)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version_spec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('modelo_version', sa.Integer(), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operacion', sa.String(length=60), nullable=False),
    sa.Column('resumen', sa.String(length=300), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], name=op.f('fk_version_spec_autor_id_usuario'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_version_spec_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_version_spec')),
    sa.UniqueConstraint('workspace_id', 'numero', name=op.f('uq_version_spec_workspace_id'))
    )
    op.create_index(op.f('ix_version_spec_workspace_id'), 'version_spec', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Borra la tabla version_spec."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_spec_workspace_id'), table_name='version_spec')
    op.drop_table('version_spec')
    # ### end Alembic commands ###
