"""tabla fuente para la ingesta

Revision ID: ff39a100be3c
Revises: 6f0f88df11ef
Create Date: 2026-09-08 16:37:27.677696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff39a100be3c'
down_revision: Union[str, Sequence[str], None] = '6f0f88df11ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea la tabla fuente (ingesta, paso 3)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('creada_por_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('nombre_tabla', sa.String(length=80), nullable=False),
    sa.Column('archivo_origen', sa.String(length=255), nullable=False),
    sa.Column('hoja', sa.String(length=120), nullable=True),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('huella', sa.String(length=16), nullable=False),
    sa.Column('esquema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ruta_parquet', sa.String(length=300), nullable=False),
    sa.Column('ruta_original', sa.String(length=300), nullable=True),
    sa.Column('opciones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estado', sa.Enum('lista', 'error', name='estado_fuente', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuario.id'], name=op.f('fk_fuente_creada_por_id_usuario'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_fuente_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fuente')),
    sa.UniqueConstraint('workspace_id', 'nombre_tabla', name=op.f('uq_fuente_workspace_id'))
    )
    op.create_index(op.f('ix_fuente_workspace_id'), 'fuente', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Borra la tabla fuente."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuente_workspace_id'), table_name='fuente')
    op.drop_table('fuente')
    # ### end Alembic commands ###
